[package]
name = "freeq"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
#ori-vst = { git = "https://github.com/ori-ui/ori-vst" }

ori-vst = { path = "../ori-vst" }

num = "0.4"
realfft = "3.4"
